app/models.py
from app import db


class Plant(db.Model):
    """The simple model of a plant and its needs"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(55))
    plant_name = db.Column(db.String(255))
    last_watered = db.Column(db.Date)
    last_fed = db.Column(db.Date)


    def __repr__(self):
        return '<Plant: {}'.format(str(self.id) + ' Name: ' + str(self.name) + ' Last Watered on: '
                                     + str(self.last_watered)
                                     )

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_mail import Mail
import logging
from logging.handlers import RotatingFileHandler
import os
from flask_bootstrap import Bootstrap


db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug:
        if not os.path.exists('logs'):
            os.mkdir('logs')

        file_handler = RotatingFileHandler('logs/app_name.log', maxBytes=10240, backupCount=50)
        file_handler.setFormatter(
            logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Your App Startup')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp
from app import db
from utils import plant_getter as pg


@bp.route('/')
@bp.route('/home')
def home():
    context = pg('shaggy')
    return render_template(
        'home.html',
        title='Home',
        **context
    )

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
{% if title %}{{ title }} -- Plant Daemon{% else %}Daemon{% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Taskmaster</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                </ul>
            </div>
        </div>
</nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
    <p>I need to learn how to use html and javascript</p>
    <p>Plant Information</p>
    <div class="row">
        <div class="col-md-4">
            <p>{{ name }} was last watered on {{ last_watered }}.</p>
        </div>
        <div class="col-md-4">
            <p>{{ name }} is a {{ plant_name }} type plant.</p>
        </div>
    </div>
        <div class="row">

    </div>

{% endblock %}